// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandbox.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage is a message sent from the Go agent to the Python sandbox.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_RunCell
	//	*ClientMessage_PromptModelResponse
	//	*ClientMessage_Cancel
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRunCell() *RunCellRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_RunCell); ok {
			return x.RunCell
		}
	}
	return nil
}

func (x *ClientMessage) GetPromptModelResponse() *PromptModelResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PromptModelResponse); ok {
			return x.PromptModelResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_RunCell struct {
	RunCell *RunCellRequest `protobuf:"bytes,1,opt,name=run_cell,json=runCell,proto3,oneof"`
}

type ClientMessage_PromptModelResponse struct {
	PromptModelResponse *PromptModelResponse `protobuf:"bytes,2,opt,name=prompt_model_response,json=promptModelResponse,proto3,oneof"`
}

type ClientMessage_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*ClientMessage_RunCell) isClientMessage_Payload() {}

func (*ClientMessage_PromptModelResponse) isClientMessage_Payload() {}

func (*ClientMessage_Cancel) isClientMessage_Payload() {}

// ServerMessage is a message sent from the Python sandbox to the Go agent.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RunCellResult
	//	*ServerMessage_Output
	//	*ServerMessage_PromptModel
	//	*ServerMessage_PromptSelf
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRunCellResult() *RunCellResult {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RunCellResult); ok {
			return x.RunCellResult
		}
	}
	return nil
}

func (x *ServerMessage) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ServerMessage) GetPromptModel() *PromptModelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PromptModel); ok {
			return x.PromptModel
		}
	}
	return nil
}

func (x *ServerMessage) GetPromptSelf() *PromptSelfRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PromptSelf); ok {
			return x.PromptSelf
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RunCellResult struct {
	RunCellResult *RunCellResult `protobuf:"bytes,1,opt,name=run_cell_result,json=runCellResult,proto3,oneof"` // Final result of a cell execution
}

type ServerMessage_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"` // Streaming output (stdout/stderr)
}

type ServerMessage_PromptModel struct {
	PromptModel *PromptModelRequest `protobuf:"bytes,3,opt,name=prompt_model,json=promptModel,proto3,oneof"`
}

type ServerMessage_PromptSelf struct {
	PromptSelf *PromptSelfRequest `protobuf:"bytes,4,opt,name=prompt_self,json=promptSelf,proto3,oneof"`
}

func (*ServerMessage_RunCellResult) isServerMessage_Payload() {}

func (*ServerMessage_Output) isServerMessage_Payload() {}

func (*ServerMessage_PromptModel) isServerMessage_Payload() {}

func (*ServerMessage_PromptSelf) isServerMessage_Payload() {}

type RunCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCellRequest) Reset() {
	*x = RunCellRequest{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCellRequest) ProtoMessage() {}

func (x *RunCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCellRequest.ProtoReflect.Descriptor instead.
func (*RunCellRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *RunCellRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RunCellResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // Combined output (legacy support)
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"` // Combined stdout
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"` // Combined stderr
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCellResult) Reset() {
	*x = RunCellResult{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCellResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCellResult) ProtoMessage() {}

func (x *RunCellResult) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCellResult.ProtoReflect.Descriptor instead.
func (*RunCellResult) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *RunCellResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCellResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunCellResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunCellResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsStderr      bool                   `protobuf:"varint,2,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *Output) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Output) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

type PromptModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // Correlation ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptModelRequest) Reset() {
	*x = PromptModelRequest{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptModelRequest) ProtoMessage() {}

func (x *PromptModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptModelRequest.ProtoReflect.Descriptor instead.
func (*PromptModelRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *PromptModelRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PromptModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // Correlation ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptModelResponse) Reset() {
	*x = PromptModelResponse{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptModelResponse) ProtoMessage() {}

func (x *PromptModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptModelResponse.ProtoReflect.Descriptor instead.
func (*PromptModelResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *PromptModelResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *PromptModelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PromptSelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptSelfRequest) Reset() {
	*x = PromptSelfRequest{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptSelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptSelfRequest) ProtoMessage() {}

func (x *PromptSelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptSelfRequest.ProtoReflect.Descriptor instead.
func (*PromptSelfRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *PromptSelfRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\n" +
	"sandbox.v1\"\xdf\x01\n" +
	"\rClientMessage\x127\n" +
	"\brun_cell\x18\x01 \x01(\v2\x1a.sandbox.v1.RunCellRequestH\x00R\arunCell\x12U\n" +
	"\x15prompt_model_response\x18\x02 \x01(\v2\x1f.sandbox.v1.PromptModelResponseH\x00R\x13promptModelResponse\x123\n" +
	"\x06cancel\x18\x03 \x01(\v2\x19.sandbox.v1.CancelRequestH\x00R\x06cancelB\t\n" +
	"\apayload\"\x94\x02\n" +
	"\rServerMessage\x12C\n" +
	"\x0frun_cell_result\x18\x01 \x01(\v2\x19.sandbox.v1.RunCellResultH\x00R\rrunCellResult\x12,\n" +
	"\x06output\x18\x02 \x01(\v2\x12.sandbox.v1.OutputH\x00R\x06output\x12C\n" +
	"\fprompt_model\x18\x03 \x01(\v2\x1e.sandbox.v1.PromptModelRequestH\x00R\vpromptModel\x12@\n" +
	"\vprompt_self\x18\x04 \x01(\v2\x1d.sandbox.v1.PromptSelfRequestH\x00R\n" +
	"promptSelfB\t\n" +
	"\apayload\"$\n" +
	"\x0eRunCellRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"q\n" +
	"\rRunCellResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"9\n" +
	"\x06Output\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tis_stderr\x18\x02 \x01(\bR\bisStderr\"<\n" +
	"\x12PromptModelRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"A\n" +
	"\x13PromptModelResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"-\n" +
	"\x11PromptSelfRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rCancelRequest2P\n" +
	"\aSandbox\x12E\n" +
	"\tRunStream\x12\x19.sandbox.v1.ClientMessage\x1a\x19.sandbox.v1.ServerMessage(\x010\x01BHZFgithub.com/mariozechner/coding-agent/session/pkg/sandbox/api;sandboxv1b\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sandbox_proto_goTypes = []any{
	(*ClientMessage)(nil),       // 0: sandbox.v1.ClientMessage
	(*ServerMessage)(nil),       // 1: sandbox.v1.ServerMessage
	(*RunCellRequest)(nil),      // 2: sandbox.v1.RunCellRequest
	(*RunCellResult)(nil),       // 3: sandbox.v1.RunCellResult
	(*Output)(nil),              // 4: sandbox.v1.Output
	(*PromptModelRequest)(nil),  // 5: sandbox.v1.PromptModelRequest
	(*PromptModelResponse)(nil), // 6: sandbox.v1.PromptModelResponse
	(*PromptSelfRequest)(nil),   // 7: sandbox.v1.PromptSelfRequest
	(*CancelRequest)(nil),       // 8: sandbox.v1.CancelRequest
}
var file_sandbox_proto_depIdxs = []int32{
	2, // 0: sandbox.v1.ClientMessage.run_cell:type_name -> sandbox.v1.RunCellRequest
	6, // 1: sandbox.v1.ClientMessage.prompt_model_response:type_name -> sandbox.v1.PromptModelResponse
	8, // 2: sandbox.v1.ClientMessage.cancel:type_name -> sandbox.v1.CancelRequest
	3, // 3: sandbox.v1.ServerMessage.run_cell_result:type_name -> sandbox.v1.RunCellResult
	4, // 4: sandbox.v1.ServerMessage.output:type_name -> sandbox.v1.Output
	5, // 5: sandbox.v1.ServerMessage.prompt_model:type_name -> sandbox.v1.PromptModelRequest
	7, // 6: sandbox.v1.ServerMessage.prompt_self:type_name -> sandbox.v1.PromptSelfRequest
	0, // 7: sandbox.v1.Sandbox.RunStream:input_type -> sandbox.v1.ClientMessage
	1, // 8: sandbox.v1.Sandbox.RunStream:output_type -> sandbox.v1.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	file_sandbox_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_RunCell)(nil),
		(*ClientMessage_PromptModelResponse)(nil),
		(*ClientMessage_Cancel)(nil),
	}
	file_sandbox_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RunCellResult)(nil),
		(*ServerMessage_Output)(nil),
		(*ServerMessage_PromptModel)(nil),
		(*ServerMessage_PromptSelf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
