# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sandbox_pb2 as sandbox__pb2


class SandboxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunStream = channel.stream_stream(
                '/sandbox.v1.Sandbox/RunStream',
                request_serializer=sandbox__pb2.ClientMessage.SerializeToString,
                response_deserializer=sandbox__pb2.ServerMessage.FromString,
                _registered_method=True)


class SandboxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunStream(self, request_iterator, context):
        """RunStream establishes a bidirectional stream for executing code and receiving events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RunStream,
                    request_deserializer=sandbox__pb2.ClientMessage.FromString,
                    response_serializer=sandbox__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.v1.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.v1.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sandbox.v1.Sandbox/RunStream',
            sandbox__pb2.ClientMessage.SerializeToString,
            sandbox__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
