# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sandbox.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsandbox.proto\x12\nsandbox.v1\"\xdf\x01\n\rClientMessage\x12\x37\n\x08run_cell\x18\x01 \x01(\x0b\x32\x1a.sandbox.v1.RunCellRequestH\x00R\x07runCell\x12U\n\x15prompt_model_response\x18\x02 \x01(\x0b\x32\x1f.sandbox.v1.PromptModelResponseH\x00R\x13promptModelResponse\x12\x33\n\x06\x63\x61ncel\x18\x03 \x01(\x0b\x32\x19.sandbox.v1.CancelRequestH\x00R\x06\x63\x61ncelB\t\n\x07payload\"\x94\x02\n\rServerMessage\x12\x43\n\x0frun_cell_result\x18\x01 \x01(\x0b\x32\x19.sandbox.v1.RunCellResultH\x00R\rrunCellResult\x12,\n\x06output\x18\x02 \x01(\x0b\x32\x12.sandbox.v1.OutputH\x00R\x06output\x12\x43\n\x0cprompt_model\x18\x03 \x01(\x0b\x32\x1e.sandbox.v1.PromptModelRequestH\x00R\x0bpromptModel\x12@\n\x0bprompt_self\x18\x04 \x01(\x0b\x32\x1d.sandbox.v1.PromptSelfRequestH\x00R\npromptSelfB\t\n\x07payload\"$\n\x0eRunCellRequest\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\"q\n\rRunCellResult\x12\x16\n\x06output\x18\x01 \x01(\tR\x06output\x12\x16\n\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x18\n\x07success\x18\x04 \x01(\x08R\x07success\"9\n\x06Output\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n\tis_stderr\x18\x02 \x01(\x08R\x08isStderr\"<\n\x12PromptModelRequest\x12\x16\n\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\"A\n\x13PromptModelResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\"-\n\x11PromptSelfRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"\x0f\n\rCancelRequest2P\n\x07Sandbox\x12\x45\n\tRunStream\x12\x19.sandbox.v1.ClientMessage\x1a\x19.sandbox.v1.ServerMessage(\x01\x30\x01\x42HZFgithub.com/mariozechner/coding-agent/session/pkg/sandbox/api;sandboxv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/mariozechner/coding-agent/session/pkg/sandbox/api;sandboxv1'
  _globals['_CLIENTMESSAGE']._serialized_start=30
  _globals['_CLIENTMESSAGE']._serialized_end=253
  _globals['_SERVERMESSAGE']._serialized_start=256
  _globals['_SERVERMESSAGE']._serialized_end=532
  _globals['_RUNCELLREQUEST']._serialized_start=534
  _globals['_RUNCELLREQUEST']._serialized_end=570
  _globals['_RUNCELLRESULT']._serialized_start=572
  _globals['_RUNCELLRESULT']._serialized_end=685
  _globals['_OUTPUT']._serialized_start=687
  _globals['_OUTPUT']._serialized_end=744
  _globals['_PROMPTMODELREQUEST']._serialized_start=746
  _globals['_PROMPTMODELREQUEST']._serialized_end=806
  _globals['_PROMPTMODELRESPONSE']._serialized_start=808
  _globals['_PROMPTMODELRESPONSE']._serialized_end=873
  _globals['_PROMPTSELFREQUEST']._serialized_start=875
  _globals['_PROMPTSELFREQUEST']._serialized_end=920
  _globals['_CANCELREQUEST']._serialized_start=922
  _globals['_CANCELREQUEST']._serialized_end=937
  _globals['_SANDBOX']._serialized_start=939
  _globals['_SANDBOX']._serialized_end=1019
# @@protoc_insertion_point(module_scope)
